image: node:6.9.1
before_script:
  - echo -en "\n60.191.93.169 r.widget-inc.com" >> /etc/hosts
  - cp test/conf/config{.sample,}.js
  - npm config set registry "https://registry.npm.taobao.org"
  - npm config set @upyun:registry "http://r.widget-inc.com"
  - npm install

variables:
  NODE_ENV: test

cache:
  key: $CI_BUILD_REF
  paths:
    - node_modules

stages:
  # - lint
  - test

# lint:
#   stage: lint
#   script:
#     - npm run lint
#   tags:
#     - offline-test

test:
  services:
    - mysql
    - memcached
  variables:
    MYSQL_ROOT_PASSWORD: ''
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  stage: test
  script:
    - bin/init-database.coffee
    - npm run test-cov
  tags:
    - offline-test