before_script:
  - npm install
  - "cp test/conf/config{.sample,}.js"

variables:
  NODE_ENV: 'test'

stages:
  - lint
  - test

lint_job:
  stage: lint
  script:
    - npm run lint
  tags:
    - 'discover'

test_job:
  stage: test
  script:
    - npm run test-cov
  tags:
    - 'discover'